=== MbqIIB/IIBFlows/workspace/libGetCustomer_v1/GetCustomer/GetCustomerResponse.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="ExtensionListType">
    	<xsd:sequence>
    		<xsd:element ref="extension"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="ExtensionType">
    	<xsd:sequence>
    		<xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="value" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:element name="extension" type="ExtensionType"></xsd:element>

    <xsd:element name="operationName" type="xsd:string"></xsd:element>


    <xsd:element name="timestamp" type="xsd:string"></xsd:element>

    <xsd:element name="sourceSystem" type="xsd:string"></xsd:element>

    <xsd:element name="userId" type="xsd:string"></xsd:element>

    <xsd:complexType name="HeaderType">
    	<xsd:sequence>
    		<xsd:element ref="operationName" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element ref="timestamp" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element ref="sourceSystem" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element ref="userId" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element ref="extension" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="ErrorType">
    	<xsd:sequence>
    		<xsd:element name="Code" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="Description" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="TimeStamp" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
    		<xsd:element name="Application" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
    		<xsd:element name="SourceSystem" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
    		<xsd:element name="Severity" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="GetCustomerResponseType">
    	<xsd:sequence>
    		<xsd:element ref="Header" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:choice>
    			<xsd:element ref="Error" maxOccurs="0" minOccurs="0"></xsd:element>

                <xsd:element ref="Body" minOccurs="1" maxOccurs="1"></xsd:element>
            </xsd:choice>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Header" type="HeaderType"></xsd:element>


    <xsd:element name="GetCustomerResponse"
    	type="GetCustomerResponseType">
    </xsd:element>


    <xsd:element name="Error" type="ErrorType"></xsd:element>

    <xsd:element name="CustomerId" type="xsd:string"></xsd:element>

    <xsd:element name="CompanyName" type="xsd:string"></xsd:element>

    <xsd:complexType name="AddressType">
    	<xsd:sequence>
    		<xsd:element name="AddressLine1" type="xsd:string"></xsd:element>
    		<xsd:element name="AddressLine2" type="xsd:string"></xsd:element>
    		<xsd:element name="AddressLine3" type="xsd:string"></xsd:element>
    		<xsd:choice>
    			<xsd:element name="PostCode" type="xsd:string"></xsd:element>
    			<xsd:element name="ZipCode" type="xsd:string"></xsd:element>

    		</xsd:choice>
    		<xsd:element name="City" type="xsd:string"></xsd:element>
    		<xsd:element name="Country" type="xsd:string"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="BodyType">
    	<xsd:sequence>
    		<xsd:element ref="CustomerId"></xsd:element>
    		<xsd:element ref="CompanyName"></xsd:element>
    		<xsd:element ref="Address"></xsd:element>
    		<xsd:element ref="Telephone"></xsd:element>
    		<xsd:element name="emailAddress" type="eMailType"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Address" type="AddressType"></xsd:element>

    <xsd:element name="Body" type="BodyType"></xsd:element>

    <xsd:complexType name="TelephoneType">
 		<xsd:sequence>
    		<xsd:element ref="Number"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>


    <xsd:element name="Telephone" type="TelephoneType"></xsd:element>



    <xsd:complexType name="NumberType">
    	<xsd:sequence>
    		<xsd:element name="value" type="xsd:string" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute ref="type"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:attribute name="type" type="xsd:string"></xsd:attribute>
    <xsd:element name="Number" type="NumberType"></xsd:element>
    

    <xsd:complexType name="eMailType">
    	<xsd:sequence>
    		<xsd:element name="email" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="eMailAddress" type="eMailType"></xsd:element>
</xsd:schema>

=== MbqIIB/IIBFlows/workspace/libGetCustomer_v1/GetCustomer/GetCustomerResponse3.xml
<?xml version="1.0" encoding="UTF-8"?>
<GetCustomerResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GetCustomerResponse.xsd">
  <Header>
    <operationName>operationName</operationName>
    <timestamp>timestamp</timestamp>
    <sourceSystem>sourceSystem</sourceSystem>
    <userId>userId</userId>
    <extension>
      <name>name</name>
      <value>value</value>
    </extension>
  </Header>
  <Body>
    <CustomerId>CustomerId</CustomerId>
    <CompanyName>CompanyName</CompanyName>
    <Address>
      <AddressLine1>AddressLine1</AddressLine1>
      <AddressLine2>AddressLine2</AddressLine2>
      <AddressLine3>AddressLine3</AddressLine3>
      <PostCode>PostCode</PostCode>
      <City>City</City>
      <Country>Country</Country>
    </Address>
    <Telephone>
      <Number type="">
        <value>value</value>
      </Number>
    </Telephone>
    <emailAddress>
      <email>email</email>
    </emailAddress>
  </Body>
</GetCustomerResponse>

=== MbqIIB/IIBFlows/workspace/libGetCustomer_v1/GetCustomer/GetCustomerResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<GetCustomerResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GetCustomerResponse.xsd">
  <Header>
    <operationName>operationName</operationName>
    <timestamp>timestamp</timestamp>
    <sourceSystem>sourceSystem</sourceSystem>
    <userId>userId</userId>
    <extension>
      <name>name</name>
      <value>value</value>
    </extension>
  </Header>
  <Error>
    <Code>Code</Code>
    <Description>Description</Description>
    <TimeStamp>TimeStamp</TimeStamp>
    <Application>Application</Application>
    <SourceSystem>SourceSystem</SourceSystem>
    <Severity>Severity</Severity>
  </Error>
</GetCustomerResponse>
